---
################
# docker build #
################
kind: pipeline
type: docker
name: docker-build-arm64

platform:
  os: linux
  arch: arm64

trigger:
  event:
  - tag

# anchors
cr_secrets: &cr_secrets
  username:
    from_secret: cr-44net-username
  password:
    from_secret: cr-44net-key

docker_build: &docker_build
  image: plugins/docker
  pull: if-not-exists
  group: build

# build steps arm64
steps:
- name: 'debian-s6: build and publish docker image'
  <<: *docker_build
  settings:
    repo: cr.44net.ch/baseimages/debian-s6
    registry: cr.44net.ch
    context: debian-s6
    dockerfile: debian-s6/Dockerfile.arm64
    auto_tag: true
    auto_tag_suffix: linux-arm64
    <<: *cr_secrets

- name: 'debian-s6-slim: build and publish docker image'
  <<: *docker_build
  settings:
    repo: cr.44net.ch/baseimages/debian-s6-slim
    registry: cr.44net.ch
    context: debian-s6-slim
    dockerfile: debian-s6-slim/Dockerfile.arm64
    auto_tag: true
    auto_tag_suffix: linux-arm64
    <<: *cr_secrets

---
kind: pipeline
type: docker
name: docker-build-amd64

platform:
  os: linux
  arch: amd64

trigger:
  event:
  - tag

# anchors
cr_secrets: &cr_secrets
  username:
    from_secret: cr-44net-username
  password:
    from_secret: cr-44net-key

docker_build: &docker_build
  image: plugins/docker
  pull: if-not-exists
  group: build

# build steps amd64
steps:
- name: 'debian-s6: build and publish docker image'
  <<: *docker_build
  settings:
    repo: cr.44net.ch/baseimages/debian-s6
    registry: cr.44net.ch
    context: debian-s6
    dockerfile: debian-s6/Dockerfile.amd64
    auto_tag: true
    auto_tag_suffix: linux-amd64
    <<: *cr_secrets

- name: 'debian-s6-slim: build and publish docker image'
  <<: *docker_build
  settings:
    repo: cr.44net.ch/baseimages/debian-s6-slim
    registry: cr.44net.ch
    context: debian-s6-slim
    dockerfile: debian-s6-slim/Dockerfile.amd64
    auto_tag: true
    auto_tag_suffix: linux-amd64
    <<: *cr_secrets

---
kind: pipeline
type: docker
name: docker-publish-manifest

platform:
  os: linux
  arch: amd64

trigger:
  event:
  - tag

# anchors
cr_secrets: &cr_secrets
  username:
    from_secret: cr-44net-username
  password:
    from_secret: cr-44net-key

# build steps
steps:
- name: 'debian-s6: publish manifest'
  image: plugins/manifest
  settings:
    spec: debian-s6/manifest.tmpl
    auto_tag: true
    ignore_missing: true
    <<: *cr_secrets

- name: 'debian-s6-slim: publish manifest'
  image: plugins/manifest
  settings:
    spec: debian-s6-slim/manifest.tmpl
    auto_tag: true
    ignore_missing: true
    <<: *cr_secrets

depends_on:
  - docker-build-amd64
  - docker-build-arm64

