###########################
# publish docker manifest #
###########################
# branch: master
# event: tag

depends_on:
  - publish_docker_debians6
  - publish_docker_debians6slim
  - publish_docker_debianbase

clone:
  git:
    when:
      #branch: master
      event: tag
    image: woodpeckerci/plugin-git

pipeline:

  # debian-s6 - publish docker manifest for automatic multi arch pulls
  publish-manifest-debian-s6:
    when:
      #branch: master
      event: tag
    image: plugins/manifest
    pull: true
    settings:
      spec: debian-s6/manifest.tmpl
      auto_tag: true
      ignore_missing: true
      username:
        from_secret: cr-44net-username
      password:
        from_secret: cr-44net-key

  # debian-s6-slim - publish docker manifest for automatic multi arch pulls
  publish-manifest-debian-s6-slim:
    when:
      #branch: master
      event: tag
    image: plugins/manifest
    pull: true
    settings:
      spec: debian-s6-slim/manifest.tmpl
      auto_tag: true
      ignore_missing: true
      username:
        from_secret: cr-44net-username
      password:
        from_secret: cr-44net-key

  # debian-base - publish docker manifest for automatic multi arch pulls
  publish-manifest-debian-base:
    when:
      #branch: master
      event: tag
    image: plugins/manifest
    pull: true
    settings:
      spec: debian-base/manifest.tmpl
      auto_tag: true
      ignore_missing: true
      username:
        from_secret: cr-44net-username
      password:
        from_secret: cr-44net-key

