#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# shellcheck disable=SC1112
# shellcheck disable=SC2016
# shellcheck disable=SC1073
# shellcheck disable=SC1004


# set pid/gid or leave on default
: "${PUID:=4444}"
: "${PGID:=4444}"

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

echo '
-------------------------------------------------
   ___   ___            _                ____ 
  /   | /   |          | |              / ___|
 / /| |/ /| |_ __   ___| |_ ______ ___ / /___ 
/ /_| / /_| | ’_ \ / _ \ __|______/ __|| ___ \
\___  \___  | | | |  __/ |_       \__ \| \_/ |
    |_/   |_/_| |_|\___|\__|      |___/\_____/
                                              
 _                    _                            
| |                  (_)                           
| |__   __ _ ___  ___ _ _ __ ___   __ _  __ _  ___ 
| ’_ \ / _` / __|/ _ \ | ’_ ` _ \ / _` |/ _` |/ _ \
| |_) | (_| \__ \  __/ | | | | | | (_| | (_| |  __/
|_.__/ \__,_|___/\___|_|_| |_| |_|\__,_|\__, |\___|
                                         __/ |     
                                        |___/      
                                                                                                                                                                           
git.gsqnet.ch/44net-assets/docker-baseimage-debian-s6'
echo "
-------------------------------------------------
GID/UID
-------------------------------------------------
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------------------
"
